FAMNM/famnm-website

about/org-structure.html
events/ftc-kickoff.html
events/rqb.html
sponsor/teams.html

- Two carousels under Events had not been upgraded
- Fix tabs where they are used

bootstrap 4: fix lingering update issues

---

about/index.html
css/main.css
teams/maker-works.html

- Hyphenate justified text on mobile.
- Change wording on Maker Works page to indicate we don't make a mock
field anymore

mobile: make text more readable on some pages.

---

events/famnm-forums.html
js/web-encapsulation.js

Update the FAMNM Forum page with a few details of this year's event.
`js/web-encapsulation.js` was broken by the update to Bootstrap 4 -- this fixes it so it works again.

Fix some JS and update Forums page

---

events/famnm-forums.html
js/forums.js

Adds a map and a schedule for FAMNM Forums.

FAMNM Forums: Add details

---

events/famnm-forums.html

Ellen is unable to make it so her presentation is being replaced with a pre presentation panel.

update first presentation of forums to panel

---

events/famnm-forums.html

* Add Ellen's slide deck under an "Extra Resources" section
* Update blurb
* Support linking a single presentation resource to each presentation (using the `item[0].link` property in the schedule variable)

forums: more page updates

---

events/famnm-forums.html

Added a link to the presentations folder of the Google Drive and also updated the text on the link to the twitch channel.

Update forums page to be post-event

---

events/kickoff.html
js/kickoff/page.js
js/kickoff/teamlist.json

- Add latitude and longitude for missing rooms
- Update team not found message
- Comment out campus tours

kickoff: update schedule and team list

---

js/kickoff/page.js

kickoff: fix KOP pickup location

---

events/ri3d/index.html

This fixes excessive margins around the images on the ri3d index page, and add separators to the sections on mobile.

ri3d: fix layout issues for WebKit/Blink

---

css/main.css
sponsor/corporate.html

The biggest change is limiting the scope of preventing hyperlink word wrapping.

Fixes to the Corporate Sponsorship page

---

.github/PULL_REQUEST_TEMPLATE/hotfix.md
.github/PULL_REQUEST_TEMPLATE/main.md

purposes.
(none of the above apply to this pull request)
As per the new Pull Request Guidelines, this request just adds two pull request templates to the repostiory, which need to be on gh-pages in order for them to take effect. We can modify them as needed later, but I think the sooner we can roll this out the better.

Add pull request templates.

---

_includes/footer.html
_includes/header.html

Add a link to the FAMNM LinkedIn page, on both the footer and the Media section of the navbar.

Add LinkedIn to the social media accounts

---

_includes/footer.html

purposes.
This uses a modified version of the Unstyled MailChimp signup form embedded in the footer. Confirmation message appears in a popup window (Not great UX but we'd need to embed MailChimp JS to make it work without).

Include mailing list signup form

---

_includes/footer.html

Adds the text `you@example.com` as a placeholder to the mailing list signup form so people know what to put in the text box.

footer: Add email placeholder text

---

sponsor/member.html
teams/resources.html

purposes.
Refactor pages that use the blur-on-rollover to show text into simple tabbed interfaces, bringing them in line with the Coding Style Guide. Closes #73.

Don't use fancy rollovers

---

_config.yml

This updates the `_config.yml` file to use the official [`famnm.webmaster@umich.edu`](mailto:famnm.webmaster@umich.edu) email instead of Paul's email

update config YML

---

_includes/footer.html
_includes/header.html

Replace the defunct Flickr link with a link to the FAMNM Google Photos page.

Replace Flickr with Google Photos

---

_includes/footer.html
events/frc-offseason.html

purposes.
Combo of #89 and #90 (squashed). Will check that the youtube link works as expected on mobile shortly.

A couple small fixes (offseason title, youtube channel name)

---

events/frc-offseason.html

purposes.
We have a new contact email for the event. Also a TBA page.

Offseason updates

---

events/ri3d/index.html
sponsor/corporate.html
sponsor/member.html
sponsor/teams.html

purposes.
styled so as not to clash visually with the rest of the site. (The doc isn't updated but I didn't change anything visual)
Updated all the email addresses on the non Core Team pages to match famnm's new email addresses.
I don't have a testing environment set up, would someone who does mind clicking the emails to see if they work before approving this PR?

Update page emails

---

_includes/footer.html
about/core.html

Anuraag's email was listed as his personal UM email (anuraagb@umich.edu), so that was updated to be "famnm.vp@umich.edu".
Additionally, a "Contact us" button was added to the footer of the website which will send mail to the newly acquired "famnm@umich.edu" email.

Update VP Email on Core Team Page, add "Contact us" button to Footer

---

sponsor/orgs.html

:warning: WIP COMMIT, DO NOT MERGE UNTIL THIS HAS BEEN UPDATED WITH THE FINAL CONTENT:warning:
purposes.
This PR adds content to the "Get Involved As A Student Org" page, as drafted by Amanda.
It includes a table of FAMNM's events. On smaller viewports, this table is within a scrollable div and so does not appear to be loaded off the side of the page.

Add Content to "Get Involved As A Student Org" page

---

.gitignore
events/ftc-kickoff.html

See #97 for more details on this PR. This is to merge the changes into `gh-pages`.

"Get Involved As A Student Org" page to gh-pages

---

_includes/footer.html
_includes/header.html

Change google photos link to public photos

---

.gitignore
events/ri3d/index.html

Rearrange Ri3D page to place recruitment & sponsorship information at the top

---

index.html

WRC is done. The banner should not be on the homepage anymore.

Remove WRC Banner

---

events/ftc-kickoff.html

FTC Kickoff registration is closed. The event page should be updated to reflect that.

Remove link to registration form with registration closed.

---

events/ftc-kickoff.html

Re-adding the FTC Kickoff 2019 registration form to the event's page, as we're re-opening registration for a little while longer.

re-add ftc kickoff registration form

---

.gitignore
events/ftc-kickoff.html

-->
Update the FTC Kickoff page after the event, with the link to the presentation materials!
Another PR incoming once we have event photos processed.

post ftc kickoff 2019 event page update

---

_includes/footer.html
_includes/scripts.html

This adds a link to donate to the FIRST Scholarship Fund in the footer of the website.

Add link to donate to scholarship

---

events/robotics-day.html

purposes.
This PR updates the robotics day event page with the schedule for the 2019 event.

robotics day 2019 schedule

---

events/robotics-day.html

purposes.
No more event description in Robotics Day team building exercise table entries. (Per Austin's request)

No more team building descriptions

---

css/main.css

In #119 we pushed a change which made the font size too big. This PR removes that change.

Fix the global font size on the website

---

events/ri3d/2020.html

purposes.
Added buttons linking to the (public view-only) 2020 MRi3D Documentation Google Drive & GitHub pages

Add technical documentation links to Ri3D page

---

_includes/footer.html
_includes/header.html
css/main.css
events/frc-offseason.html
events/ftc-kickoff.html
events/kickoff.html
events/ri3d/2020.html
events/ri3d/index.html
events/robotics-day.html
members/calendar.html
sponsor/orgs.html

purposes.
All buttons are now btn-secondary, and footer background matches header background

Button & footer formatting

---

events/kickoff.html
events/ri3d/team.html
js/kickoff/teamlist.json

There was a missing `</div>` tag in the page.

FRC KICKOFF 2020 TEAM INFO

---

events/ri3d/2020.html

Place official robot photo on ri3d documentation page

Update Ri3D documentation page with pretty robot picture

---

events/ri3d/2020.html

Change title from 2019 to 2020

Update 2020 Ri3D Documentation page title

---

events/kickoff.html

purposes.
This removes the schedule, map, and countdown from the kickoff page and adds the link to the feedback form.

update kickoff page with feedback form (post kickoff-2020)

---

_includes/footer.html
_includes/header.html
about/index.html
events/frc-offseason.html
events/ftc-kickoff.html
events/kickoff.html
events/ri3d/2019.html
events/ri3d/index.html
events/robotics-day.html

For security, we added `rel="noopener noreferrer"` to every link on our website with `target="_blank"`. For more info on why, please read [this article](https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/).

add rel="noopener noreferrer" on all target="_blank" links

---

_includes/header.html
css/main.css

I borked the navbar when doing rebrand stuff. This fixes that.

hotfix: navbar broken after rebranding

---

attendance/index.html
attendance/view.html

Gotta use HTTPS on the backend!

[hotfix] new https URL for famnm backend

---

css/main.css
events/frc-offseason.html
events/ftc-kickoff.html
events/kickoff.html
events/robotics-day.html
events/rqb.html
index.html

purposes.
The event pages were updated with short blurbs explaining that FAMNM plans to be completely virtual this year. An "alert" banner was added to the front page explaining the same.

Update FAMNM Event pages for new school year

---

_includes/header.html
scholarship.html

purposes.
This pull request adds the FIRST Scholarship FAQ page (`scholarship.html`) to the website.

Add Scholarship page

---

events/ftc-kickoff.html

purposes.
This pull request adds a notice to the FTC Kickoff page that we'll be hosting Kickoff on September 18, as well as a link to the registration form.

Add registration form to FTC Kickoff page

---

attendance/index.html
attendance/view.html

purposes.
The FAMNM attendance tracker reborn! Now on the front-end as well!
Right now it does all the basics and it does them well, but there's still plenty of room to add new stuff (such as the ability to edit existing meetings).
[Pull request #14 from the backend repo](https://github.com/FAMNM/famnm-website-backend/pull/14) should be merged before this one.

Rebirth of the Attendance Tracker

---

_includes/header.html

Adds a link to [the Invensity registration form](https://forms.gle/W6NytySr1vcd1SfZ6) in the navigation bar.

Add Invensity registration form link

---

_includes/footer.html
about/index.html
about/org-structure.html
events/frc-offseason.html
events/ftc-kickoff.html
events/kickoff.html
events/rqb.html
index.html
js/org-structure.js
members/calendar.html
scholarship.html
sponsor/corporate.html
sponsor/member.html
sponsor/orgs.html
teams/freelance.html
teams/resources.html

Co-authored-by: Michael Peng <michael@mcmoo.org>
purposes.
This pull request makes all pages on the website accessible in reader view in accordance with our DEI plan.

Meet accessibility goals of the website

---

_includes/header.html

Invensity registration is no longer active.

Remove Invensity registration form link

---

events/ftc-kickoff.html

Raise the unit price for pizza from $11.98 to $12.70. Replace "begin" with "start" in the last checklist item for consistency.

FTC Kickoff 2022: Raise pizza unit price

---

Gemfile.lock
attendance/index.html

* Doesn't show a warning about uniqname format if the uniqname field is empty.
* Modal hides correctly after submitting.
* Gives some info about green uniqnames on the confirmation page.
* Does a final check that a meeting type has been selected right before submission.

Attendance Tracker Fixes

---

index.html

purposes.
Replaced the Offseason Event volunteer sheet with the FRC Kickoff volunteer sheet on the front page.

Add the 2023 FRC Kickoff volunteer sign-up sheet to the front page

---

robots.txt

Add robots.txt to comply with web conventions. Prevent bots from crawling the attendance record as it is volatile.

Add robots.txt prohibiting crawling attendance

---

scholarship.html

This adds a new question and answer to the Scholarship FAQ page in order to highlight the link to donate to the FIRST Scholarship Fund.

Add donation question to scholarship FAQ

---

events/kickoff.html
js/kickoff/page.js

Add the list of student organizations to the FRC kickoff page in the traditional format plus links to orgs' websites (if available)

FRC kickoff: Add org fair org list

---

src/components/index/Announcements.astro
src/pages/events/kickoff.astro
src/pages/events/ri3d/index.astro
src/pages/teams/freelance.astro

purposes.
- Change tense on FRC kickoff page to refer to the past
- Point to the game materials, Notion resources page, and mentoring request form from the FRC kickoff page
- Change tense on homepage FRC kickoff announcement to refer to the past
- Point to Ri3D livestreams from homepage
- Add announcement on Ri3D page that points to the Twitch channel for 2024 streams
- Have Freelance Mentoring page link to the mentoring request form

2024 FRC Post-kickoff

---

src/components/Footer.astro
src/components/SponsorList.astro
src/components/index/Announcements.astro
src/pages/events/kickoff.astro
src/pages/events/ri3d/index.astro
src/pages/index.astro

purposes.
- Replaced the first two images on the FRC kickoff page's carousel with 2024 pictures
- Added `title` and `aria-label` to sponsor logo links for accessibility
- Added link to Ri3D's 2024 playlist
- Added 2023 and 2022 links to "Previous Seasons" on the Ri3D page
- Changed the GBM term and location on the homepage to Winter 2024 and EECS 3427
- Change the volunteering spreadsheet link on the homepage to point to 2024 FRC …

Add 2024 FRC kickoff images, update GBM and Ri3D info

---

pnpm-lock.yaml
src/components/Footer.astro
src/pages/events/ri3d/index.astro

Regenerate lockfile

---

pnpm-lock.yaml

Force regenerate pnpm-lock.yaml

---

src/pages/offseason.astro

Reverts FAMNM/famnm-website#233
Will put back when its actually open lol

Revert "update registration"

---

src/components/Footer.astro
src/pages/offseason.astro

Change to scheduling and sponsors.

needed offseason changes

---

src/pages/offseason.astro

open registration

---

src/pages/offseason.astro

hot fix, added team list. Updated to 8 pm 4/28.

Added Team List

---

src/pages/offseason.astro

* [ x] This update has been tested thoroughly enough to ensure there are no
* [ x] This update has been tested in both desktop and mobile layouts.
* [ x] This update does not break any existing functionality, layout, or style
* [x ] This update is free of any code intended only for debugging or testing
purposes.
* [x ] This update follows the FAMNM Website Code Style Guide.
* [x ] This update meets the visual style requirements as specified in the
styled so as not to clash visually with the rest …

updated team list and made it dynamic

---

src/pages/offseason.astro

Quick team list update, one line change

update registration list

---

src/pages/offseason.astro

Updated Team List for May 4th. Also made the blue on the text a tad lighter to make it stand out more.

updated team list

---

src/pages/offseason.astro

added 8015

---

src/pages/offseason.astro

Added Rob and ESG logos below FAQ. Also updated team list (Thursday, May 29). 
12 Insertions on offseason.astro

added logos and updated team list

---

src/pages/events/ftc-kickoff.astro

added address
